[editor]
line-number = "relative"
mouse = false
shell = ["zsh", "-c"]
# cursorline = true
true-color = true
undercurl = true
bufferline = "always"
color-modes = true

[editor.statusline]
left = ["mode", "spacer", "version-control"]
right = ["file-modification-indicator", "diagnostics", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
charactor = "▏"

[keys.insert]
j = { k = "normal_mode" }
